apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: # kpt-merge: example/coredns-caching
  name: coredns-caching
  namespace: cachingdns-distribution
  annotations:
    internal.kpt.dev/upstream-identifier: 'autoscaling|HorizontalPodAutoscaler|example|coredns-caching'
spec:
  maxReplicas: 40
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 95
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coredns-caching
